server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:inudev5/spring-cloud-config.git
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEA1REbLR0Zko5W5ryORtiHrnUzP8ZzzRRmJ3QguBH+Uk+vZ7or
            AexE25qI9MUASDT+uXcl4NxXA4/GJTyNiKdu4peuS2RmV1sWR09Q/Ozr7hPVH1aN
            gDtxTlvbmSJ0hF1fQqV6xPrCwdi14ITmsgqBRQzxmjqRUTGJ6Ygok78xkuGfPx4a
            8b6GerbOr+MfjkiLXoY6f2t9PyFqZ2yHqmfz2gw3zW3tBxSmg77lLTYJyjRTnFNk
            /H0pXQ9GQqKW47JIxa/Wbm3yiNCHNQDdMR+/Aq0xCyfgXRGSNO9kX0/7NckzS5uZ
            PUrWYiA+eFqYFKHR9eC3Fsid9RAKy61jdV4kvNnWJUS/zK5qwaUY6msq23xlCMkk
            BZjISFPE5PyfrndR8LW6VfflGC5VyLI8o4DjECq2czRnCe25Qhw3D6tK28hIf4xi
            5bcPWLsq5ltHH6oOSWvqjYJMF2ZnOAE/MQqAGTAHeRJnoNWw0c37un418E/AE0MT
            2jFl03nYhp70tUABaH92bVxOsWFkGCbSvWmzlYXfeh5V5CaSNhlwxd5/ge6PMVgY
            +KN3+5dXiza88eCaDFjqsR6pQM+UaMFEFMRBfbacFhshabKLJ7Qz9/5k5F7Uvvl8
            RWYie4Bg/UPC0GrqOJ0JZVeKtZpGJlh3kOfzplTit7XtRiDFQrf8NxmaujcCAwEA
            AQKCAgAqzPXlmRvi+d7xGN2H08VlwTtbS1VF1Bw1Prm34D1zcXht4NL03u5yItfy
            O4Sz/JlSzmF4iyqbl40ZO9G+qsu2jvu/P1rjn3OZPZCqTjmSqL8+PVfNc6NuNzuk
            xmwbjtos/CruWOU4pXzbrjbdewi+wzvhXHSGl+n5VJW6IEUoGVSxDC4jc7919TUN
            1hUnsuD0SwiDQid1wBOs1PtnutwcaCnphXSA4KAWhQlqjJlo2hwVohb+NXJStFfL
            2PdwpAbEV28+3a1D2IfgmNzWGmd3dS0N7aO/bmEtaw2BrAJtqo44WPhufJMWQR3r
            dV9pfZw8xThiRkicyu0wPxNkp1W/kDRSHR+WA7Uhnc0A/3c9kutZzKUd0SBSWxRn
            cFg7Ov3Lp8OPQLD7/CcAGT2cBYb920j+vajN9gDu5dMUFPgYLHtOZHFMsBmytGFc
            K2evVF3GN9NnrWFEzuFcebDs6MFgF+i+rf7jteFZuNpQc9z3Bm491bD+Slg0kSsG
            WmYeT5/zdWHSKNEVy2quKi7Nk+UbiYgzF7IJDqEW2623cxjZfBj418qww7H1Oap1
            mlV6Z5bFveEHsrw4GzqrJK3WhuqE19htL1FMevko2AW1tMuRwPgbVyR2B9kDeeyh
            MQhsWdIviGGl1gAvOq7h+p1f4tnDBO9NXt1XuIo5an8NjkA/OQKCAQEA7qwPpcXO
            37f1v3fYtFSTzoIhTlfm+vKiiyApIHzdiZS4yUpPOUly2t5Gp86oFpZ60FzHJqH+
            X0Rsndstprc3pDDqnY0PuablCktR89uOcpjDuoMyu4Jt225n2D+2TubYkWDR5R6J
            1qIMKBLzzc325WZikw/lAMjM5Hni9eMK/bRP1YfSTBgvuR4ghdkcBnecYun+7xtJ
            35BbvHCkIJoLD8ThghIWo8+ODXcTMemCBl5UYCO3OS7Agu2yc9RPMHbp8vtPh1rB
            29jQwT3UDQDKXQSJGCiUtz7lxjyYueSRE9yrb2Wortqc3KRAxCjF44mFIhWH+1tB
            /Nx1J5GszMy/swKCAQEA5IkltpbWDht8GA8Jk6zIU9rq5vRwydtCCjzigMScZuxI
            jtyXGmLaD0CWyM6GHgidKiXUcuUoNBNk/JSCjxpgUsV8PfcL2JwQZpIjFIbft5Vc
            04m0e5fR3rNxsWGDD8rIdeB98CNGJ/hIBrVRQReMxAcek0w8rzagn5sfxdbUIVEF
            0IueGpeRB2kw9PEAU5E7uZbAARAUhK9954ncnd0hXpPEtUUx348NlRVk7Wl2yw/1
            t9B0T3VF/jtdn87gLvwmAbZXFOxxMQcqGq2JQ3wMOqy3Ztzu4iCFUPqVKKrnYiBe
            Kt/0l02ewv9H2OKbpMTdatZR5Ct89RrqNni8BCj5bQKCAQAvbzDY8HxSCDymJgqC
            pICPvVsjN+MnIsvdPLIPy+E3s8AZ+VPPfeJ+z0hZl3/epV+ZQ6cs7WshwfaYVPQ4
            uxcq4bHvSBbE/f9tUVTjU1J3Qhc8XVDa5Wwx/TpURy1Tdxu5oPV2ROB+MMybtlCQ
            KYwVQYj701/fDQlzqynJVqtbiteHB6xrBS+O6gbqsyCXxHPnULwjB1hiP02MIRLt
            i9AA/U8YS8IGIn0H/g9pjxARdfPs+4wxqDIIk3cxABQQ/ME4UmwW6Zm3uNqcXU5k
            mzCc1gbtLzuHQ8/k2yw7XcrbmLLVu+2PetFMJLTeh3/03eMAyCizcwqlV6dNCu29
            8j9zAoIBAQCQOVkajMBTsNa0nDDQCFd4TAy4agUP7pYTve63ktydO3pi5iVZ2o6A
            16MQ4PzU0VzV73/Obn3bt22g1Nw8EUo+kjDhLhpEveC/ynPnDWL8CX/GY/4JjXs9
            zwLuDXrXqYKumVkBBlHNAav6x8yahpEoWNHb5V3auV/OuefoQ7YlvGst/B5v67zz
            71edDMbG9j251sAfK5W3UsTjLSaUXawkcp7OQvfBfRb2QcUq6sa0ScMpGJ1+U6Uz
            VyWzp6vlGu2lYPw90SVx6nKQ2XlppExXbw5jFQSQojNgMnOVcZ2KWKD079b88VhC
            +TXPUtsktbSCKvUNSMCYMj8i1zjYaz9VAoIBAEPoHkVY1gwaAtq5mYxgiA1JDugv
            fze6C36t0bi47bsWZ5sHGOOJUM0Z50Z2FeRD+ZZ++n/SbkbDh/7xJ2fzYsQuGg0y
            0kXWT1YBjfvfc40RvMnQmzmUEh1DPTBhJaMDM8SyO1NM3k5N6T4xv9tFMHE+JWO/
            zdD7Pr2OCzgISpD+ieLqjDX2Fw2+m0a2y6iHZ4XNsiFQW2FENCaxluzfe7wM1cBG
            u2MLrYcq3wtmqUlqPLswKI3uOSe1elRl05/a1QtKZmu7PjLa82yjnYkpwq4tFN3f
            vWDb8B/UvGF6idTLPhZZVVnNBgl+mIAq8z20FuqYPNfqWr1laA7k1nbxAKA=
            -----END RSA PRIVATE KEY-----
          ignoreLocalSshSettings: true

